[project]
name = "aifactory_os"
version = "0.1.0"

[tool.hatch.build.targets.wheel]
packages = ["agents", "clients", "core", "shared"]

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = "-ra -vv"